# -*- coding: utf-8 -*-
"""SmartCredit-ML.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1s5sjoQ294Tvi6QUJh3G6jv7C49xV7fAl

**SmartCredit-ML: Sistema de Scoring Predictivo para Riesgo
Financiero**
"""

# 1. Importación de librerías esenciales
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score

# 2. Carga del Dataset (Asegúrate de subir el archivo 'credit_risk_dataset.csv' a Colab)
# Puedes descargarlo de: https://www.kaggle.com/datasets/laotse/credit-risk-dataset
try:
    df = pd.read_csv('credit_risk_dataset.csv')
    print("Dataset cargado con éxito.")
except FileNotFoundError:
    print("Error: Sube el archivo 'credit_risk_dataset.csv' a la carpeta de archivos de Colab (icono de carpeta a la izquierda).")

# Eliminamos outliers de edad y antigüedad laboral
df = df[df['person_age'] < 95]
df = df[df['person_emp_length'] < 60]
print(f"Dataset limpio: {len(df)} registros.")

# 4. Definición de Features y Target
X = df.drop('loan_status', axis=1) # Todas las columnas menos el target
y = df['loan_status']              # Lo que queremos predecir (0=Paga, 1=Default)

# Separación en entrenamiento y prueba (80/20)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

# 5. Pipeline de Preprocesamiento (Scikit-learn)
# Identificamos columnas por tipo
numeric_features = X.select_dtypes(include=['int64', 'float64']).columns
categorical_features = X.select_dtypes(include=['object']).columns

# Transformador para números: Imputar nulos con la mediana + Escalar
numeric_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='median')),
    ('scaler', StandardScaler())
])

# Transformador para categorías: OneHot Encoding
categorical_transformer = Pipeline(steps=[
    ('onehot', OneHotEncoder(handle_unknown='ignore'))
])

# Unificador de transformaciones
preprocessor = ColumnTransformer(
    transformers=[
        ('num', numeric_transformer, numeric_features),
        ('cat', categorical_transformer, categorical_features)
    ])

# 6. Definición del Modelo (XGBoost)
# Usamos scale_pos_weight porque hay menos morosos que pagadores (clases desbalanceadas)
model = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', XGBClassifier(n_estimators=100, learning_rate=0.1, max_depth=5, scale_pos_weight=4))
])

# 7. Entrenamiento y Evaluación
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

print("\n--- REPORTE DE CLASIFICACIÓN ---")
print(classification_report(y_test, y_pred))
print(f"ROC-AUC Score: {roc_auc_score(y_test, model.predict_proba(X_test)[:, 1]):.4f}")

import joblib

# Guardamos el pipeline completo (incluye el preprocesamiento y el modelo)
joblib.dump(model, 'smartcredit_model_landa.pkl')
print("Modelo 'smartcredit_model_landa.pkl' listo para descargar.")